## * Consider the below code to answer further questions:

In [13]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Ans 1. Yes, There is a difference between list_ and array_list 
## A list can contain any type of data but An array contains only similar type of data.


In [7]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [12]:
## Ans 2.
print("Data Types of each element in list_")
for i in list_:
    print(type(i))
print("Data Types of each element in array_list")    
for i in array_list:
    print(type(i))

Data Types of each element in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data Types of each element in array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:


In [21]:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. Consider the below code to answer further questions:


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


## Ans 3. Yes, There is a difference between the elements of list_ and array_list. Now the data type of elements of array_list becomes 'Integer'

In [22]:
for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [30]:
## Ans 4.
print(f'Shape of num array is {np.shape(num_array)}')
print(f'Size of num array is {np.size(num_array)}')


Shape of num array is (2, 3)
Size of num array is 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [36]:
## Ans 5.
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [37]:
## Ans 6.
print(np.identity(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
